export const homeProducts = [
    {
        name: "Nike Dunk Low",
        price: 200,
        category: "Men/Women",
        image: "https://res.cloudinary.com/djpdesqrs/image/upload/v1737556404/sneaker1_fymfn9.png",
        rating: 2.5,
        index: 1,
        width: 220,
        height: 220,
        slug: "max-1",
        isFeatured: true,
        mobileheight: 300,
        mobilewidth: 300,
        countInStock: 20,
        quantity: 0,
        color: ["Red", "Blue", "Black"],
        sizes: [38, 39, 40, 41, 42, 43, 44, 45]
    },
    {
        name: "Fila Destructor",
        price: 200,
        category: "Men/Women",
        image: "https://res.cloudinary.com/djpdesqrs/image/upload/v1737556404/sneaker2_u5gjpe.png",
        rating: 4,
        index: 2,
        width: 220,
        height: 220,
        slug: "max-2",
        isFeatured: true,
        mobileheight: 300,
        mobilewidth: 300,
        countInStock: 20,
        quantity: 0,
        color: ["Red", "Blue", "Black"],
        sizes: [38, 39, 40, 41, 42, 43, 44, 45]
    },
    {
        name: "Nike Air Force 1",
        price: 200,
        category: "Men/Women",
        image: "https://res.cloudinary.com/djpdesqrs/image/upload/v1737556407/sneaker3_rixldl.png",
        rating: 4,
        index: 3,
        width: 220,
        height: 220,
        slug: "max-3",
        isFeatured: true,
        mobileheight: 300,
        mobilewidth: 300,
        countInStock: 20,
        quantity: 0,
        color: ["Red", "Blue", "Black"],
        sizes: [38, 39, 40, 41, 42, 43, 44, 45]
    },
    {
        name: "Converse Chuck Taylor",
        price: 200,
        category: "Men/Women",
        image: "https://res.cloudinary.com/djpdesqrs/image/upload/v1737556410/sneaker4_medibp.png",
        rating: 4,
        index: 4,
        width: 150,
        height: 150,
        slug: "max-4",
        isFeatured: true,
        mobileheight: 300,
        mobilewidth: 300,
        countInStock: 20,
        quantity: 0,
        color: ["Red", "Blue", "Black"],
        sizes: [38, 39, 40, 41, 42, 43, 44, 45]
    },
    {
        name: "Nike React Infinity Run",
        price: 200,
        category: "Men/Women",
        image: "https://res.cloudinary.com/djpdesqrs/image/upload/v1737556406/sneaker5_ijfvfv.png",
        rating: 5,
        index: 5,
        width: 220,
        height: 220,
        slug: "max-5",
        isFeatured: true,
        mobileheight: 300,
        mobilewidth: 300,
        countInStock: 20,
        quantity: 0,
        color: ["Red", "Blue", "Black"],
        sizes: [38, 39, 40, 41, 42, 43, 44, 45]
    },
    {
        name: "Air Force Max",
        price: 200,
        category: "Men/Women",
        image: "https://res.cloudinary.com/djpdesqrs/image/upload/v1737556408/sneaker6_raxv6w.png",
        rating: 5,
        index: 6,
        width: 220,
        height: 220,
        slug: "max-6",
        isFeatured: true,
        mobileheight: 300,
        mobilewidth: 300,
        countInStock: 20,
        quantity: 0,
        color: ["Red", "Blue", "Black"],
        sizes: [38, 39, 40, 41, 42, 43, 44, 45]
    },
    {
        name: "Nike Leather",
        price: 200,
        category: "Men/Women",
        image: "https://res.cloudinary.com/djpdesqrs/image/upload/v1737556411/sneaker7_epljct.png",
        rating: 5,
        index: 7,
        width: 260,
        height: 260,
        slug: "max-7",
        isFeatured: true,
        mobileheight: 300,
        mobilewidth: 300,
        countInStock: 20,
        quantity: 0,
        color: ["Red", "Blue", "Black"],
        sizes: [38, 39, 40, 41, 42, 43, 44, 45]
    },
    {
        name: "Nike Leather",
        price: 200,
        category: "Children",
        image: "https://res.cloudinary.com/djpdesqrs/image/upload/v1737556409/sneaker8_lkrmai.png",
        rating: 5,
        index: 8,
        width: 220,
        height: 220,
        slug: "max-8",
        isFeatured: true,
        mobileheight: 300,
        mobilewidth: 300,
        countInStock: 20,
        quantity: 0,
        color: ["Red", "Blue", "Black"],
        sizes: [38, 39, 40, 41, 42, 43, 44, 45]
    },
    {
        name: "Nike Leather Air",
        price: 200,
        category: "Children",
        image: "https://res.cloudinary.com/djpdesqrs/image/upload/v1737556411/sneaker9_s0ymz3.png",
        rating: 5,
        index: 9,
        width: 220,
        height: 220,
        slug: "max-9",
        isFeatured: false,
        mobileheight: 300,
        mobilewidth: 300,
        countInStock: 20,
        quantity: 0,
        color: ["Red", "Blue", "Black"],
        sizes: [38, 39, 40, 41, 42, 43, 44, 45]
    },
    {
        name: "Puma Fill On",
        price: 200,
        category: "Men",
        image: "https://res.cloudinary.com/djpdesqrs/image/upload/v1737556432/sneaker10_c59cad.png",
        rating: 5,
        index: 10,
        width: 220,
        height: 220,
        slug: "max-10",
        isFeatured: false,
        mobileheight: 300,
        mobilewidth: 300,
        countInStock: 20,
        quantity: 0,
        color: ["Red", "Blue", "Black"],
        sizes: [38, 39, 40, 41, 42, 43, 44, 45]
    },
    {
        name: "Converse Chuck Taylor",
        price: 200,
        category: "Men",
        image: "https://res.cloudinary.com/djpdesqrs/image/upload/v1737556412/sneaker11_x07eav.png",
        rating: 5,
        index: 11,
        width: 220,
        height: 220,
        slug: "max-11",
        isFeatured: false,
        mobileheight: 300,
        mobilewidth: 300,
        countInStock: 20,
        quantity: 0,
        color: ["Red", "Blue", "Black"],
        sizes: [38, 39, 40, 41, 42, 43, 44, 45]
    },
    {
        name: "Converse Chuck Taylor",
        price: 200,
        category: "Men",
        image: "https://res.cloudinary.com/djpdesqrs/image/upload/v1737556412/sneaker12_japvej.png",
        rating: 5,
        index: 12,
        width: 220,
        height: 220,
        slug: "max-12",
        isFeatured: false,
        mobileheight: 300,
        mobilewidth: 300,
        countInStock: 20,
        quantity: 0,
        color: ["Red", "Blue", "Black"],
        sizes: [38, 39, 40, 41, 42, 43, 44, 45]
    },
    {
        name: "Converse Chuck Taylor",
        price: 200,
        category: "Men",
        image: "https://res.cloudinary.com/djpdesqrs/image/upload/v1737556402/sneaker13_lvwpla.png",
        rating: 5,
        index: 13,
        width: 220,
        height: 220,
        slug: "max-13",
        isFeatured: false,
        mobileheight: 300,
        mobilewidth: 300,
        countInStock: 20,
        quantity: 0,
        color: ["Red", "Blue", "Black"],
        sizes: [38, 39, 40, 41, 42, 43, 44, 45]
    },
    {
        name: "Converse Chuck Taylor",
        price: 200,
        category: "Men",
        image: "https://res.cloudinary.com/djpdesqrs/image/upload/v1737556405/sneaker16_khtg7v.png",
        rating: 5,
        index: 14,
        width: 220,
        height: 220,
        slug: "max-14",
        isFeatured: false,
        mobileheight: 300,
        mobilewidth: 300,
        countInStock: 20,
        quantity: 0,
        color: ["Red", "Blue", "Black"],
        sizes: [38, 39, 40, 41, 42, 43, 44, 45]
    },
    {
        name: "Converse Chuck Taylor",
        price: 200,
        category: "Men",
        image: "https://res.cloudinary.com/djpdesqrs/image/upload/v1737556405/sneaker15_f2g5pj.png",
        rating: 5,
        index: 15,
        width: 220,
        height: 220,
        slug: "max-15",
        isFeatured: false,
        mobileheight: 300,
        mobilewidth: 300,
        countInStock: 20,
        quantity: 0,
        color: ["Red", "Blue", "Black"],
        sizes: [38, 39, 40, 41, 42, 43, 44, 45]
    }
]

export const shoeSizes = [
    { size: 38 },
    { size: 39 },
    { size: 40 },
    { size: 41 },
    { size: 42 },
    { size: 43 },
    { size: 44 },
    { size: 45 }
    
]

export const shoeColors = [
    { color: "Black", hex: 'bg-black', id: 0 },
    { color: "Blue", hex: 'bg-blue-600', id: 1 },
    { color: "Green", hex: 'bg-green-500', id: 2 },
    { color: "Gray", hex: 'bg-gray-500', id: 3 },
    { color: "Yellow", hex: 'bg-yellow-500', id: 4 },
    { color: "Red", hex: 'bg-red-600', id: 5 },
    { color: "Silver", hex: 'bg-slate-300', id: 6 }
]

export const handleLogout = async ({dispatch, router}) => {
    try {
      const response = await fetch('http://localhost:4000/api/logout', {
        method: 'POST',
        credentials: 'include' // Required for cookie clearing
      });

      if (response.ok) {
        // Clear client-side state
        dispatch({ type: 'CLEAR_CART' });
        localStorage.removeItem('userState');
        
        // Redirect
        router.push('/login');
        router.refresh(); // Force Next.js cache invalidation
      }
    } catch (error) {
      console.error('Logout failed:', error);
    }
};